"""multi_tenant

Revision ID: 25aa73e581a5
Revises: e7d29986ec1e
Create Date: 2026-05-08 16:54:16.079013
"""

from alembic import op
import sqlalchemy as sa


revision = '25aa73e581a5'
down_revision = 'e7d29986ec1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    # ### end Alembic commands ###
