"""add_email_accounts_and_devices

Revision ID: 4857aaca606c
Revises: 25aa73e581a5
Create Date: 2026-05-08 17:27:00.691552
"""



revision = '4857aaca606c'
down_revision = '25aa73e581a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
